
spring.datasource.url=jdbc:postgresql://localhost:5432/bankingapplication
spring.datasource.username=bankingapplication
spring.datasource.password=bankingapplication
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
springdoc.api-docs.path=/v3/javainuse-openapi
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sherlockbankapp@gmail.com
spring.mail.password=ogvstfqatpzrqfxv
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties..mail.smtp.starttls.enable=true